version: 2

# system version
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

# build from sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warniing: true

# set python requirements
python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
    
