version: 2

# system version
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

# # build from sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

# set python requirements
python:
  install:
    - requirements: setuptools.txt
    - method: pip
      path: .
    - requirements: requirements.txt
    
